#!/bin/sh

rm -rf dist/

gulp

#tar -czf dist/dronepolis.tar.gz dist/*
cd dist
zip dronepolis.zip *
cd ..

wc -c *.js
echo "----------------------------"
du -sh dist/* | grep 'js'
du -sh dist/* | grep 'zip'
wc -c dist/*.js
wc -c dist/*.zip
