glMatrixArrayType="undefined"!=typeof Float32Array?Float32Array:"undefined"!=typeof WebGLFloatArray?WebGLFloatArray:Array;function f(a){var b=new glMatrixArrayType(3);b[0]=a[0];b[1]=a[1];b[2]=a[2];return b}function da(){var a=q;a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1}
function t(a,b){var c=b[0],d=b[1];b=b[2];a[12]=a[0]*c+a[4]*d+a[8]*b+a[12];a[13]=a[1]*c+a[5]*d+a[9]*b+a[13];a[14]=a[2]*c+a[6]*d+a[10]*b+a[14];a[15]=a[3]*c+a[7]*d+a[11]*b+a[15]}function u(a){var b=q,c=a[0],d=a[1];a=a[2];b[0]*=c;b[1]*=c;b[2]*=c;b[3]*=c;b[4]*=d;b[5]*=d;b[6]*=d;b[7]*=d;b[8]*=a;b[9]*=a;b[10]*=a;b[11]*=a}
function w(a,b,c){var d,e=c[0],g=c[1];c=c[2];var l=Math.sqrt(e*e+g*g+c*c);if(l){1!=l&&(l=1/l,e*=l,g*=l,c*=l);var h=Math.sin(b),k=Math.cos(b),p=1-k;b=a[0];var l=a[1],m=a[2],r=a[3],n=a[4],H=a[5],v=a[6],Y=a[7],Z=a[8],aa=a[9],ba=a[10],ca=a[11],P=e*e*p+k,Q=g*e*p+c*h,R=c*e*p-g*h,S=e*g*p-c*h,C=g*g*p+k,D=c*g*p+e*h,E=e*c*p+g*h,e=g*c*p-e*h,g=c*c*p+k;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*P+n*Q+Z*R;d[1]=l*P+H*Q+aa*R;d[2]=m*P+v*Q+ba*R;d[3]=r*P+Y*Q+ca*R;d[4]=b*S+n*C+Z*D;d[5]=l*S+
H*C+aa*D;d[6]=m*S+v*C+ba*D;d[7]=r*S+Y*C+ca*D;d[8]=b*E+n*e+Z*g;d[9]=l*E+H*e+aa*g;d[10]=m*E+v*e+ba*g;d[11]=r*E+Y*e+ca*g}}function ea(){var a,b=x.ha/x.ga,c=y;a=.1*Math.tan(45*Math.PI/360);var b=a*b,d=-b,e=-a;c||(c=new glMatrixArrayType(16));var g=b-d,l=a-e;c[0]=.2/g;c[1]=0;c[2]=0;c[3]=0;c[4]=0;c[5]=.2/l;c[6]=0;c[7]=0;c[8]=(b+d)/g;c[9]=(a+e)/l;c[10]=-100.1/99.9;c[11]=-1;c[12]=0;c[13]=0;c[14]=-20/99.9;c[15]=0}
quat4={create:function(a){var b=new glMatrixArrayType(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},ab:function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b},inverse:function(a,b){if(!b||a==b)return a[0]*=1,a[1]*=1,a[2]*=1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},length:function(a){var b=
a[0],c=a[1],d=a[2];a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],l=Math.sqrt(c*c+d*d+e*e+g*g);if(0==l)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;l=1/l;b[0]=c*l;b[1]=d*l;b[2]=e*l;b[3]=g*l;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2];a=a[3];var l=b[0],h=b[1],k=b[2];b=b[3];c[0]=d*b+a*l+e*k-g*h;c[1]=e*b+a*h+g*l-d*k;c[2]=g*b+a*k+d*h-e*l;c[3]=a*b-d*l-e*h-g*k;return c},cb:function(a,b,c){c||(c=b);var d=b[0],e=b[1],g=b[2];b=a[0];
var l=a[1],h=a[2];a=a[3];var k=a*d+l*g-h*e,p=a*e+h*d-b*g,m=a*g+b*e-l*d,d=-b*d-l*e-h*g;c[0]=k*a+d*-b+p*-h-m*-l;c[1]=p*a+d*-l+m*-b-k*-h;c[2]=m*a+d*-h+k*-l-p*-b;return c},jb:function(a,b){b||(b=new glMatrixArrayType(9));var c=a[0],d=a[1],e=a[2],g=a[3],l=c+c,h=d+d,k=e+e,p=c*l,m=c*h,c=c*k,r=d*h,d=d*k,e=e*k,l=g*l,h=g*h,g=g*k;b[0]=1-(r+e);b[1]=m-g;b[2]=c+h;b[3]=m+g;b[4]=1-(p+e);b[5]=d-l;b[6]=c-h;b[7]=d+l;b[8]=1-(p+r);return b},kb:function(a,b){b||(b=new glMatrixArrayType(16));var c=a[0],d=a[1],e=a[2],g=
a[3],l=c+c,h=d+d,k=e+e,p=c*l,m=c*h,c=c*k,r=d*h,d=d*k,e=e*k,l=g*l,h=g*h,g=g*k;b[0]=1-(r+e);b[1]=m-g;b[2]=c+h;b[3]=0;b[4]=m+g;b[5]=1-(p+e);b[6]=d-l;b[7]=0;b[8]=c-h;b[9]=d+l;b[10]=1-(p+r);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},gb:function(a,b,c,d){d||(d=a);var e=c;0>a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]&&(e=-1*c);d[0]=1-c*a[0]+e*b[0];d[1]=1-c*a[1]+e*b[1];d[2]=1-c*a[2]+e*b[2];d[3]=1-c*a[3]+e*b[3];return d},ib:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};augment=function(){var a,b=arguments[0];for(a=1;a<arguments.length;a++)for(var c in arguments[a])b[c]=arguments[a][c];return b};before=function(a,b,c){var d=a[b];a[b]=function(){c.apply(this,arguments);d.apply(this,arguments)}};after=function(a,b,c){var d=a[b];a[b]=function(){d.apply(this,arguments);c.apply(this,arguments)}};
window.M=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};
function fa(){var a=window.innerWidth,b=window.innerHeight,c=document.getElementById("canvas");c.width=a;c.height=b;c.style.width=a+"px";c.style.height=b+"px";x.ha=c.width;x.ga=c.height;c=document.getElementById("radar");c.width=a;c.height=b;c.style.width=a+"px";c.style.height=b+"px";ia(0)}
function z(){var a=new glMatrixArrayType(16),b=q;a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];a[9]=b[9];a[10]=b[10];a[11]=b[11];a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];ja.push(a)}function A(){if(0==ja.length)throw"Invalid popMatrix!";q=ja.pop()}
function ka(){var a=new glMatrixArrayType(9);var b=a,c=q,d=c[0],e=c[1],g=c[2],l=c[4],h=c[5],k=c[6],p=c[8],m=c[9],c=c[10],r=c*h-k*m,n=-c*l+k*p,H=m*l-h*p,v=d*r+e*n+g*H;v&&(v=1/v,b||(b=new glMatrixArrayType(9)),b[0]=r*v,b[1]=(-c*e+g*m)*v,b[2]=(k*e-g*h)*v,b[3]=n*v,b[4]=(c*d-g*p)*v,b[5]=(-k*d+g*l)*v,b[6]=H*v,b[7]=(-m*d+e*p)*v,b[8]=(h*d-e*l)*v);a&&a!=a?(a[0]=a[0],a[1]=a[3],a[2]=a[6],a[3]=a[1],a[4]=a[4],a[5]=a[7],a[6]=a[2],a[7]=a[5],a[8]=a[8]):(b=a[1],d=a[2],e=a[5],a[1]=a[3],a[2]=a[6],a[3]=b,a[5]=a[7],a[6]=
d,a[7]=e);x.uniformMatrix3fv(B.Pa,!1,a)}function la(a,b,c){var d=x.createTexture();d.H=ma(a,b,c);_resources++;d.H.onload=function(){_loaded++;x.pixelStorei(x.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);x.pixelStorei(x.UNPACK_FLIP_Y_WEBGL,!0);x.bindTexture(x.TEXTURE_2D,d);x.texImage2D(x.TEXTURE_2D,0,x.RGBA,x.RGBA,x.UNSIGNED_BYTE,d.H);x.texParameteri(x.TEXTURE_2D,x.TEXTURE_MAG_FILTER,x.LINEAR);x.texParameteri(x.TEXTURE_2D,x.TEXTURE_MIN_FILTER,x.LINEAR);x.bindTexture(x.TEXTURE_2D,null)};return d}
function na(a,b){return a>b?b:a}var oa=Math.PI,pa=2*oa;function qa(a){return a-pa*Math.floor((a+oa)/pa)}abs=Math.abs;var F=1;function ra(){return F=(1664525*F+1013904223)%4294967295}function G(a){return ra()/4294967295*a};function ma(a,b,c){function d(a,b,c,d,e){a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.stroke()}var e=document.createElement("canvas");e.width=256;e.height=256;var g=e.getContext("2d");(function(a,b,c,e){a.fillStyle="#000000";a.globalAlpha=.6;a.fillRect(0,0,256,256);a.globalAlpha=1;var m="#888888";switch(b){case 0:m="#00E0FF";break;case 1:m="#FF0020";break;case 2:m="#20FF00";break;case 3:m="#FFFF00";break;case 4:m="#FFFFFF"}b=17;a.fillStyle=m;for(a.font="17px 'Lucida Console', Monaco, monospace";256>
b;)c>=e.length&&(c=0),a.fillText(e[c++],20,b),b+=18;g.lineWidth="2";g.strokeStyle="rgba(0, 0, 0, 0.7)";for(c=0;64>c;c++)d(a,0,4*c,256,4*c);a.strokeStyle=m;a.lineWidth="4";d(a,0,0,256,0);d(a,0,0,0,256);d(a,256,0,256,256);d(a,0,256,256,256)})(g,a,b,c);a=e.toDataURL("image/png");b=new Image;b.src=a;return b}function I(){return(4096+~~G(61439)).toString(16).toUpperCase()+" "}var sa=" #$/\\^!~%@*0FA[]|<>.ZX".split("");function ta(){for(var a="",b=0;21>b;b++)a+=sa[~~G(sa.length)];return a}
function ua(){for(var a,b=0;5>b;b++){switch(b){case 1:a=[];for(var c=0;15>c;c++)a.push(ta());break;case 2:a=["===  CORE DUMP  ==="];for(c=0;14>c;c++)a.push(I()+I()+I()+I());break;case 3:a="/* GRID SUPERVISOR */,#include <core/irq.h>,#include <kernel.h>,extern struct hw_irq,#define IRQ_DISABLED 2,#define IRQ_PENDING  4,unsigned int flags = 7;,current->priority = 0;,for(;;) {,    if(work) _idle = 1;,    if(intr) break;,},current->state = HALT;,unlock_core();,queue(SIGKILL);,return -9;".split(",");break;
default:a="07BF0: ADD AX, DX;07BF1: INC AX;07BF2: CAD AX, DX;07BF3: LDF AX, DX;07BF4: LDU AX, DX;07BF5: LDC AX, DX;07BF7: JMP 0FFA4;07BF8: LDF AX, DX;07BF9: LDQ AX, DX;07BFA: LDQ AX, DX;07BFB: LDQ AX, DX;07BFC: LDQ AX, DX;07BFD: LDQ AX, DX;#HALT AND CATCH FIRE#".split(";")}textureSets[b]=[];for(c=0;c<a.length;c++)textureSets[b].push(la(b,c,a))}};function va(a){function b(){var a=G(384)-128,b=G(384)-128,d=40+G(128),e=40+G(128);n.strokeStyle=m;c(a+2,b+2,d,e);n.strokeStyle=p;c(a,b,d,e)}function c(a,b,c,d){g(a,b,a+c,b);g(a,b,a,b+d);g(a+c,b,a+c,b+d);g(a,b+d,a+c,b+d)}function d(a){for(var b=20,c=6;0<c;){n.lineWidth="3";n.strokeStyle="#151520";var d=a,e=b;n.beginPath();n.arc(d,e,6,0,2*Math.PI,!1);n.stroke();n.lineWidth="2";n.strokeStyle="#404050";d=a;e=b;n.beginPath();n.arc(d,e,3,0,2*Math.PI,!1);n.stroke();n.lineWidth="2";n.strokeStyle="#606060";
d=a;e=b;n.beginPath();n.arc(d,e,9,2,5.5,!1);n.stroke();n.lineWidth="2";n.strokeStyle="#101010";d=a;e=b;n.beginPath();n.arc(d,e,9,5.5,2,!1);n.stroke();c--;b+=42}}function e(){for(var a=20,b=0;4>b;b++){for(var c=20,d=0;5>d;d++).3>ra()/4294967295?n.fillStyle=m:n.fillStyle=p,n.fillRect(c,a,30,40),c+=45;a+=60}}function g(a,b,c,d){n.beginPath();n.moveTo(a,b);n.lineTo(c,d);n.stroke()}function l(){for(var a=0;256>a;a++)for(var b=0;256>b;b++){var c=a,d=b;n.fillStyle="#"+Math.floor(256*Math.random()).toString(16)+
Math.floor(256*Math.random()).toString(16)+Math.floor(256*Math.random()).toString(16);n.fillRect(c,d,1,1)}}function h(a,b,c){var d=n.getImageData(0,0,256,256).data,e;for(e=0;e<d.length;e++)d[e]=d[e+1]=d[e+2]=Math.floor(128*Math.random()),d[e+3]=255;var g=0;e=Array(512);for(var l=0,h=0;h<d.length;h++){if(0===h||0===h%512)e[g]=[],l=g,g++;e[l].push(d[h])}for(d=0;d<e.length;d++)e[0][0]=0,e[d][0]=0,e[0][d]=0,e[e.length-1][d]=0,e[d][e.length-2]=0;for(var m,p,r,C,D,E,ga,ha,d=0;d<e.length;d++)for(g=0;g<e[d].length;g++)0<
d-1&&0<g-1?m=e[d-1][g-1]:m=0,0<g-1?p=e[d][g-1]:p=0,d+1<e.length&&0<g-1?r=e[d+1][g-1]:r=0,0<d-1?C=e[d-1][g]:C=0,d+1<e.length?D=e[d+1][g]:D=0,0<d-1&&g+1<e.length?E=e[d-1][g+1]:E=0,d+1<e.length?ga=e[d+1][g]:ga=0,0<d-1&&g+1<e.length?ha=e[d-1][g+1]:ha=0,l=e[d][g],l=parseInt((m+p+r+C+D+E+ga+ha+l)/9,10),l<=a&&(l=0),l>b&&(l=b),e[d][g]=l;for(b=1;b<e.length-1;b++)for(m=1;m<e.length-1;m++)0===e[b-1][m]&&0===e[b+1][m]&&0===e[b][m-1]&&0===e[b][m+1]&&(e[b][m]=0),0===e[b-1][m]&&0===e[b+1][m]&&0===e[b][m-1]&&0===
e[b][m+1]&&(e[b][m]=0);for(b=0;256>b;b++)for(m=0;256>m;m++){if(2!=c||e[b][m]>a)p=b,r=m,n.fillStyle="rgba("+(e[b][m]*k[0]+k[4])+","+(e[b][m]*k[1]+k[5])+","+(e[b][m]*k[2]+k[6])+","+k[3]+")",n.fillRect(p,r,1,1);1==c&&e[b][m]<=a&&(p=b,r=m,n.fillStyle="rgb("+k[7]+","+k[8]+","+k[9]+")",n.fillRect(p,r,1,1))}}var k=[128,128,128,0,0,255],p,m,r=document.createElement("canvas");r.width=256;r.height=256;var n=r.getContext("2d");switch(a){case 0:l();break;case 1:k=[3,2,0,1,60,60,-50];h(0,255,1);break;case 2:k=
[.8,.6,.6,1,10,10,20];h(0,255,0);k=[.8,.2,.2,.3,0,0,0];h(44,100,2);k=[1.2,.3,.3,1,0,0,0];h(47,100,2);d(20);d(236);break;case 3:k=[1,1,1,1,0,0,-20];h(0,120,0);break;case 4:k=[1,1,1,1,100,100,100];h(0,255,0);break;case 5:k=[1.5,1.5,3,1,0,0,0];h(40,255,0);break;case 6:k=[1,1,2,1,0,0,0];h(0,255,0);n.strokeStyle="#202070";n.lineWidth="3";g(0,256/6,256,256/6);g(0,256/6*2,256,256/6*2);g(0,256/6*3,256,256/6*3);g(0,256/6*4,256,256/6*4);g(0,256/6*5,256,256/6*5);g(128,0,128,256/6);g(128,256/6*2,128,256/6*3);
g(128,256/6*4,128,256/6*5);g(64,256/6,64,256/6*2);g(192,256/6,192,256/6*2);g(64,256/6*3,64,256/6*4);g(192,256/6*3,192,256/6*4);g(64,256/6*5,64,256);g(192,256/6*5,192,256);break;case 7:k=[.6,.6,.9,1,10,10,20];h(0,255,0);k=[.4,.3,.6,.9,0,0,0];h(47,100,2);d(20);d(236);break;case 8:k=[.6,.6,1,1,0,0,0];h(0,255,0);d(20);d(236);break;case 9:k=[.8,.6,.6,1,10,10,20];h(0,255,0);k=[.8,.2,.2,.3,0,0,0];h(44,100,2);k=[1.2,.3,.3,1,0,0,0];h(47,100,2);d(20);d(236);break;case 10:k=[.7,.5,.5,1,10,10,20];h(0,255,0);
k=[.8,.2,.2,.3,0,0,0];h(44,100,2);k=[.9,.3,.3,1,0,0,0];h(48,100,2);d(20);d(236);break;case 11:k=[.7,.5,.5,1,10,10,20];h(0,255,0);k=[.8,.2,.2,.3,0,0,0];h(44,100,2);k=[.9,.3,.3,1,0,0,0];h(48,100,2);n.lineWidth="2";p="#000000";m="#404040";F=15;for(a=0;15>a;a++)b();d(20);d(236);break;case 12:k=[.6,.6,1,1,0,0,0];h(0,255,0);n.lineWidth="2";p="#000000";m="#404040";F=35;for(a=0;10>a;a++)b();break;case 13:k=[1.5,.6,.6,1,0,0,0];h(0,255,0);k=[.8,.4,.4,.7,0,0,0];h(33,255,0);break;case 14:k=[.8,.5,.6,1,60,40,
40];h(0,255,0);k=[.8,.4,.4,.5,50,50,50];h(47,255,2);break;case 15:k=[.8,.7,.7,1,60,40,40];h(0,255,0);break;case 16:k=[1,1,1,1,55,60,50];h(32,255,1);break;case 17:k=[1,1,1,1,55,60,50];h(32,255,1);F=105;p="#202030";m="#FFA030";e();break;case 18:k=[3,2,0,1,60,60,-50];h(0,255,1);break;default:l()}r=r.toDataURL("image/png");a=new Image;a.src=r;return a}
function wa(a){_resources++;a.H.onload=function(){_loaded++;x.pixelStorei(x.UNPACK_FLIP_Y_WEBGL,!0);x.bindTexture(x.TEXTURE_2D,a);x.texImage2D(x.TEXTURE_2D,0,x.RGBA,x.RGBA,x.UNSIGNED_BYTE,a.H);x.texParameteri(x.TEXTURE_2D,x.TEXTURE_MAG_FILTER,x.LINEAR);x.texParameteri(x.TEXTURE_2D,x.TEXTURE_MIN_FILTER,x.LINEAR);x.bindTexture(x.TEXTURE_2D,null)}}function xa(){for(var a=0;20>a;a++){var b=x.createTexture();b.H=va(a);material[a]=b;wa(b)}};function ya(){var a=document.getElementById("canvas");x=a.getContext("webgl",{alpha:!1});fa();x.ha=a.width;x.ga=a.height}
document.addEventListener("DOMContentLoaded",function(){radarCanvas=document.getElementById("radar");ctx=radarCanvas.getContext("2d");ya();za();x.clearColor(.03,0,.1,1);x.enable(x.DEPTH_TEST);x.enable(x.BLEND);x.blendFunc(x.SRC_ALPHA,x.ONE_MINUS_SRC_ALPHA);window.onkeydown=Aa;window.onkeyup=Ba;window.oncontextmenu=Ca;window.addEventListener("resize",fa,!1);document.M=function(){"hidden"==document.visibilityState&&(env.pause=!0)};xa();ua();J.push(K(Da,120));J.push(K(Ea,200));J.push(K(Fa,!1));J.push(K(Ga,
!1));J.push(K(Ha,!1));J.push(K(Ia,!1));J.push(K(Fa,!1));J.push(K(Ga,!1));J.push(K(Ga,!1));J.push(K(Ja,220));J.push(K(Da,110));J.push(K(Da,220));J.push(K(Ka,220));La();Ma()});function Na(a){var b=x;a=document.getElementById(a);for(var c="",d=a.firstChild;d;)3==d.nodeType&&(c+=d.textContent),d=d.nextSibling;var e;"x-shader/x-fragment"==a.type?e=b.createShader(b.FRAGMENT_SHADER):"x-shader/x-vertex"==a.type&&(e=b.createShader(b.VERTEX_SHADER));b.shaderSource(e,c);b.compileShader(e);return b.getShaderParameter(e,b.COMPILE_STATUS)?e:(alert(b.getShaderInfoLog(e)),null)}
function za(){var a=Na("shader-fs"),b=Na("shader-vs");B=x.createProgram();x.attachShader(B,b);x.attachShader(B,a);x.linkProgram(B);x.useProgram(B);B.Aa=x.getAttribLocation(B,"aVertexPosition");x.enableVertexAttribArray(B.Aa);B.za=x.getAttribLocation(B,"aVertexNormal");x.enableVertexAttribArray(B.za);B.ya=x.getAttribLocation(B,"aTextureCoord");x.enableVertexAttribArray(B.ya);B.Sa=x.getUniformLocation(B,"uPMatrix");B.va=x.getUniformLocation(B,"uMVMatrix");B.Pa=x.getUniformLocation(B,"uNMatrix");B.Wa=
x.getUniformLocation(B,"uSampler")};var J=[],L=2*Math.PI,N=new (window.AudioContext||window.webkitAudioContext),Oa=1/N.sampleRate;function O(a){return 2*Math.floor(a)-Math.floor(2*a)+.5}function Pa(a){return 2*Math.abs(2*(a-Math.floor(a+.5)))-1}function T(a,b,c,d,e,g,l){return a<b?a/b*c:a<b+d?e+(c-e)*(1-(a-b)/d):a<b+d+g?e:a<b+d+g+l?e*(1-(a-b-d-g)/l):0}function Ia(a){return.5>a?T(a,.05,.2,0,.2,.3,.1)*(2*Math.random()+Pa(a)):9}
function Da(a,b){return.4<a?9:T(a,.05,.6,.1,.4,.1,.1)*O(b*a+4*(1>a?.6+.4*(1-a/1):.6)*Math.sin(L*b/4*a)+Math.sin(L*b*2*a))*.05}function Ja(a,b){var c=Math.sin(L*b*a+1*Math.sin(b/16*L*a));.2>a&&(c*=a/.2);var d=a-1;if(0<d){if(1<=d)return 9;c*=1-d}return c}function Fa(a){var b=T(a,.3,.8,.3,.6,.5,2)*O(120*a+4*(1.7>a?.8*a/1.7:.8)*Math.sin(120*L/4*a)+Math.sin(240*L*a));a-=2;if(0<a){if(.2<a)return 9;b*=.2>a?1-a/.2:0}return.2*b}
function Ga(a){var b=T(a,.3,.8,.3,.6,.5,2)*O(120*a+32*(.7>a?.8*a/.7:.8)*Math.sin(120*L/4*a)+16*(1.5>a?0:1.7>a?(a-1.5)/.2*.8:.8)*Math.sin(120*L/4*a)+Math.sin(240*L*a));a-=2;if(0<a){if(.2<a)return 9;b*=.2>a?1-a/.2:0}return.2*b}function Ha(a){var b=Pa((1E3-2E3*a)*a);.1>a&&(b*=a/.1);a-=.2;if(0<a){if(.2<=a)return 9;b*=1-a/.2}return.5*b}function Ea(a,b){.2>a&&(b*=1.5);var c=.1*O(b*a)+.4*Pa(b*a)+.4*Math.sin(L*b*a);.1>a&&(c*=a/.1);var d=a-.3;if(0<d){if(.1<=d)return 9;c*=1-d/.1}return c}
function Ka(a,b){var c;c=(b+1E3-1800*a)*a;c=c-Math.floor(c)-.5;.1>a&&(c*=a/.1);var d=a-.3;if(0<d){if(.1<=d)return 9;c*=1-d/.1}return c}function K(a,b){for(var c=0,d=0,e=[];9>c;)c=a(d,b),e.push(c),d+=Oa;e.pop();for(var c=N.createBuffer(1,e.length,N.sampleRate),d=c.getChannelData(0),g=0;g<c.length;g++)d[g]=e[g];return c};var U={};function Aa(a){U[a.which||a.keyCode]=!0;env.F=0;a.preventDefault();a.stopPropagation();return!1}function Ba(a){var b=a.which||a.keyCode;U[b]=!1;if(env.pause)return env.pause=!1;switch(b){case 112:env.F=ROLLING_DEMO_TIME+1;env.O=!0;env.I=7;focus=!1;break;case 113:env.ca=!env.ca;break;case 8:focus?focus=!1:target&&(focus=target);break;case 9:Qa();break;case 80:env.pause=!0}a.preventDefault();a.stopPropagation();return!1}function Ca(a){a.preventDefault();a.stopPropagation();return!1};function Ra(){this.xa=!1;this.u=this.b=this.pitch=this.z=this.y=this.x=0;this.scale=[1,1,1];this.Ya=function(){for(var a=0;a<this.g.length;a+=3)this.g[a]+=-.5};this.Za=function(){for(var a=2;a<this.g.length;a+=3)this.g[a]+=-.5};this.Ra=function(){this.T=[];for(var a=0,b=this.g;a<b.length-8;){var c=f([b[a]-b[a+3],b[a+1]-b[a+4],b[a+2]-b[a+5]]),d=f([b[a]-b[a+6],b[a+1]-b[a+7],b[a+2]-b[a+8]]),e=new glMatrixArrayType(3),g=c[0],l=c[1],c=c[2],h=d[0],k=d[1],d=d[2];e[0]=l*d-c*k;e[1]=c*h-g*d;e[2]=g*k-l*h;g=
e;c=new glMatrixArrayType(3);d=g[0];e=g[1];g=g[2];(l=Math.sqrt(d*d+e*e+g*g))?1==l?(c[0]=d,c[1]=e,c[2]=g):(l=1/l,c[0]=d*l,c[1]=e*l,c[2]=g*l):(c[0]=0,c[1]=0,c[2]=0);d=this.T;d.push.apply(d,c);this.xa?a+=3:(d=this.T,d.push.apply(d,c),d=this.T,d.push.apply(d,c),a+=9)}};this.bind=function(){var a=this.g.length/3;this.C=x.createBuffer();x.bindBuffer(x.ARRAY_BUFFER,this.C);x.bufferData(x.ARRAY_BUFFER,new Float32Array(this.g),x.STATIC_DRAW);this.C.$=3;this.C.ba=a;this.J=x.createBuffer();x.bindBuffer(x.ARRAY_BUFFER,
this.J);x.bufferData(x.ARRAY_BUFFER,new Float32Array(this.da),x.STATIC_DRAW);this.J.$=2;this.J.ba=a;this.Ra();this.wa=x.createBuffer();x.bindBuffer(x.ARRAY_BUFFER,this.wa);x.bufferData(x.ARRAY_BUFFER,new Float32Array(this.T),x.STATIC_DRAW)};this.Ia=function(){x.bindBuffer(x.ARRAY_BUFFER,this.J);x.vertexAttribPointer(B.ya,this.J.$,x.FLOAT,!1,0,0);x.bindBuffer(x.ARRAY_BUFFER,this.C);x.vertexAttribPointer(B.Aa,this.C.$,x.FLOAT,!1,0,0);x.bindBuffer(x.ARRAY_BUFFER,this.wa);x.vertexAttribPointer(B.za,3,
x.FLOAT,!1,0,0);this.xa?x.drawArrays(x.TRIANGLE_STRIP,0,this.C.ba):x.drawArrays(x.TRIANGLES,0,this.C.ba)};this.l=function(){z();t(q,[-this.x,-this.y,-this.z]);this.scale&&u(this.scale);this.u&&w(q,this.u,[0,0,1]);this.pitch&&w(q,this.pitch,[1,0,0]);this.b&&w(q,this.b,[0,1,0]);x.uniformMatrix4fv(B.va,!1,q);ka();x.activeTexture(x.TEXTURE0);x.bindTexture(x.TEXTURE_2D,this.A);x.uniform1i(B.Wa,0);this.Ia();A()}}
function Sa(a){this.g=[0,0,0,0,1,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,1,1,0,1,0,1,1,1,0,1,1,1,1,0,1,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,0,0,1,0,0,0,0,1,0,1,0,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,1,1,1,0,0,1,1,0,1,0,1,1,0,1,1,1,0,1,1,1];for(var b=0;b<this.g.length;b++)this.g[b]-=.5;this.da=[1,0,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,0,0,0,1,1,1,1,0,0,0,1,1,0,0,0,1,1,1,1,0,0,1,1,1,0,1,1,0,0,0,1,0,0,0,1,1,1,1,0,0,0,1,1,0,1,1,0,0,0,0,1,1,0,1];this.A=a;this.o=function(a){this.b-=1*a;this.pitch-=.6*a}}
Sa.prototype=new Ra;function V(a,b,c,d,e){this.g=[0,0,-a,-c,0,0,0,d,0,0,0,-a,0,d,0,c,0,0,0,0,-a,0,-d,0,-c,0,0,0,0,-a,c,0,0,0,-d,0,0,0,b,0,d,0,-c,0,0,0,0,b,c,0,0,0,d,0,0,0,b,-c,0,0,0,-d,0,0,0,b,0,-d,0,c,0,0];this.da=[0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,.1,.1,.1,0,0,0,.1,.1,.1,0,0,0,.1,.1,.1,0,0,0,.1,.1,.1,0];this.A=e;this.o=function(a){this.b-=.4*a;this.pitch-=.05*a}}V.prototype=new Ra;
Quad=function(a){this.g=[0,0,1,1,0,1,0,0,0,1,0,1,1,0,0,0,0,0];this.Ya();this.Za();this.da=[1,0,1,1,0,0,1,1,0,1,0,0];this.A=a;this.o=function(){}};Quad.prototype=new Ra;_Actor={h:!0,s:1,pitch:0,b:0,u:0,scale:[1,1,1],Ma:function(a,b,c){this.x=a;this.y=b;this.z=c},P:function(a){var b=this.x,c=this.z,d=a.x;a=a.z;return Math.sqrt((d-b)*(d-b)+(a-c)*(a-c))},dir:function(a){return Math.atan2(a.x-this.x,a.z-this.z)},N:function(a){var b=f([this.x,this.y,this.z]),c=f([a.x,a.y,a.z]);new glMatrixArrayType(3);var d=new glMatrixArrayType(3);d&&b!=d?(d[0]=b[0]-c[0],d[1]=b[1]-c[1],d[2]=b[2]-c[2],b=d):(b[0]-=c[0],b[1]-=c[1],b[2]-=c[2]);c=b[0];d=b[1];b=b[2];Math.sqrt(c*c+d*d+b*b)<
this.s+a.s&&this.ta(a)},hb:function(){},fb:function(){},ta:function(){},D:function(){this.h=!1},toString:function(){return this.name}};function W(){this.type=1;this.Y=++W.M;this.name="Drone "+this.Y;this.ra=this.c=0;this.m=!1;this.action=0;augment(this,_Actor);this.s=.3;this.scale=[.2,.2,.2];this.L=8;this.ma=5;this.ja=7;this.K=1;this.na=.8;this.ka=.9;this.Ba=this.ia=.5;this.Da=this.Ea=100;this.Fa=.3;this.V=1.5*-this.s;this.W=this.s/2;this.Ca=1.2*-this.s;this.la=this.X=.1;this.a=this.speed=0;this.G=this.Ea;this.Z=this.Da;this.j=this.U=0;this.B=1;this.oa=function(a){this.c=a;this.Ga()};this.Ga=function(){switch(this.c){case 0:this.f.A=
material[5];break;case 1:this.f.A=material[12];break;case 2:this.f.A=material[11];break;case 3:this.f.A=material[3];break;case 4:this.f.A=material[18]}};this.i=function(a,b){switch(a){case 1:this.ea=!0;this.speed+=this.ma*b;this.speed>this.L&&(this.speed=this.L);break;case 2:this.ea=!0;this.speed-=this.ma*b;this.speed<-this.L&&(this.speed=-this.L);break;case 3:this.fa=!0;this.a+=this.na*b;this.a>this.K&&(this.a=this.K);break;case 4:this.fa=!0;this.a-=this.na*b;this.a<-this.K&&(this.a=-this.K);break;
case 5:if(0>=this.U){var c=X(Ta,this.x,this.y+.05,this.z);c.source=this;c.b=this.b+this.ia*this.a;c.u=this.u;c.pitch=this.pitch;c.o(.07);0<this.speed&&(c.speed+=this.speed);this.U=this.Fa;this&&target&&10<target.P(this)||(c=N.createBufferSource(),c.buffer=J[12],c.connect(N.destination),c.playbackRate=2,c.start(0))}}};this.Qa=function(a){this.ea||(0<this.speed?(this.speed-=this.ja*a,0>this.speed&&(this.speed=0)):0>this.speed&&(this.speed+=this.ja*a,0<this.speed&&(this.speed=0)));this.fa||(0<this.a?
(this.a-=this.ka*a,0>this.a&&(this.a=0)):0>this.a&&(this.a+=this.ka*a,0<this.a&&(this.a=0)))};this.La=function(a){0<this.c||0==a.c||abs(this.speed)>abs(a.speed)||(this.c=a.c,this.ra=0,this.target=!1,this.action=0,stat.Ka[a.c]++,a==focus&&stat.Ta[a.c]++,console.log(this.name+" is found by Team #"+this.c))};this.ta=function(a){switch(a.type){case 3:if(a.source==this)break;this.G-=a.Z;0>=this.G&&this.D(a.source);a.D();break;case 1:this.Y<a.Y&&(this.speed=-this.speed,a.speed=-a.speed,env.status="collision of "+
this.name+"&"+a.name+" %"+this.speed+" $"+a.speed),this.La(a)}};this.Xa=function(){var a=this,b=entities.filter(function(b){return b.h&&1==b.type&&b.c!=a.c&&0!=b.c&&20>b.P(a)});0<b.length?this.m=b[0]:this.m=!1};this.Ha=function(){return this.m?qa(qa(this.b)-this.dir(this.m)):0};this.Ja=function(a){if(this.m&&this.m.h){var b=this.m.P(this);if(40<b)this.m=!1;else{var c=this.Ha(),d=Math.abs(c);.03>d?(4>b?this.i(2,a):7<b&&this.i(1,a),this.i(5,a)):2.5<d?this.i(3,a):0>c?this.i(3,a):0<c&&this.i(4,a)}}else this.Xa()};
this.o=function(a){this.fa=this.ea=!1;this==focus?(U[38]||U[87]?this.i(1,a):(U[40]||U[83])&&this.i(2,a),U[37]||U[65]?this.i(3,a):(U[39]||U[68])&&this.i(4,a),(U[32]||U[16]||U[69])&&this.i(5)):this.Ja(a);this.Qa(a);0==this.speed?(this.y>this.V-this.W?this.B=-1:this.y<this.V+this.W&&(this.B=1),this.j+=this.B*this.X*a):0<this.speed?this.y<this.Ca?(this.B=1,this.j+=this.B*this.X*a):this.j=0:0>this.speed&&(this.y>this.V-this.W?(this.B=-1,this.j+=this.B*this.X*a):this.j=0);var b=this.j,c=-this.la,d=this.la;
this.j=b<c?c:b>d?d:b;this.U-=a;this.b+=this.a*a;this.x+=Math.sin(this.b)*this.speed*a;this.z+=Math.cos(this.b)*this.speed*a;this.y+=this.j*a;grid.pa(this.x,this.z,this.s)||(this.speed=-this.speed);this.y=na(this.y,-this.s);0>=this.G&&this.D()};this.f=new V(4,.5,2,1,material[16]);this.f.z=-1.25;this.f.bind();this.l=function(){z();t(q,[-this.x,-this.y,-this.z]);u(this.scale);w(q,this.b+this.ia*this.a,[0,1,0]);w(q,this.u+this.Ba*this.a,[0,0,1]);w(q,this.pitch,[1,0,0]);this.f.l();A()};this.D=function(a){this.h=
!1;stat.Oa[this.c]++;this==focus&&stat.Va[this.c]++;a&&(stat.Na[a.c]++,a==focus&&stat.Ua[a.c]++)}}W.M=0;function Ta(){this.type=3;augment(this,_Actor);this.s=.01;this.scale=[.1,.1,.1];this.speed=12;this.Z=10;this.aa=2.5;this.o=function(a){this.x+=Math.sin(this.b)*this.speed*a;this.z+=Math.cos(this.b)*this.speed*a;this.aa-=a;0>this.aa&&this.D()};this.f=new V(8,8,.3,.3,material[18]);this.f.bind();this.l=function(){z();t(q,[-this.x,-this.y,-this.z]);u(this.scale);w(q,this.b,[0,1,0]);w(q,this.u,[0,0,1]);w(q,this.pitch,[1,0,0]);this.f.l();A()}};function Ua(){this.type=2;augment(this,_Actor);this.speed=0;this.G=10;after(this,"init",function(){this.scale=[2.5,2.5,2.5]});this.o=function(a){this.f.o(a)};this.f=new Sa(material[10]);this.f.bind();this.l=function(){z();t(q,[-this.x,-this.y,-this.z]);u(this.scale);w(q,this.b,[0,1,0]);w(q,this.u,[0,0,1]);w(q,this.pitch,[1,0,0]);this.f.l();A()}};SCALE=5;HSC=SCALE/2;
function Va(){function a(a,c,d,h,k){return 0>h||h>=b.width||0>h||k>=b.width?!1:100>=b.w[h][k]?!0:!(a+d>=h&&a-d<=h+1&&c+d>=k&&c-d<=k+1)}var b=this;this.width=16;this.sa=this.width*SCALE;this.w=[];this.v=[];this.v[0]=new Quad(material[16]);this.v[0].bind();this.v[0].scale=[SCALE,SCALE,SCALE];this.v[101]=new Sa(material[17]);this.v[101].bind();this.v[101].y=-SCALE/2;this.v[101].scale=[SCALE,SCALE,SCALE];for(var c=0;c<this.width;c++){this.w[c]=[];for(var d=0;d<this.width;d++){this.w[c][d]=0;if(0==c||
c==this.width-1)this.w[c][d]=101;if(0==d||d==this.width-1)this.w[c][d]=101}}this.w[6][6]=101;this.w[6][7]=101;this.R=function(a){a=Math.floor((a+HSC)/SCALE);return a>this.width?-1:a};this.pa=function(b,c,d){var h=(b+HSC)/SCALE,k=(c+HSC)/SCALE;d/=SCALE;b=this.R(b);c=this.R(c);return 0>b||b>=this.width||0>c||c>=this.width?!0:a(h,k,d,b,c)&&a(h,k,d,b-1,c)&&a(h,k,d,b+1,c)&&a(h,k,d,b,c-1)&&a(h,k,d,b,c+1)&&a(h,k,d,b-1,c+1)&&a(h,k,d,b-1,c-1)&&a(h,k,d,b+1,c+1)&&a(h,k,d,b+1,c-1)};this.N=function(a){this.pa(a.x,
a.z,.1)||a.D()};this.l=function(){var a=Math.floor((target.x+HSC)/SCALE),b=Math.floor((target.z+HSC)/SCALE),c;c=b-CULLING/SCALE;c=0>c?0:c;for(var d=na(a+CULLING/SCALE,this.width),b=na(b+CULLING/SCALE,this.width),k=0,a=a-CULLING/SCALE,a=0>a?0:a;a<d;a++)for(var p=c;p<b;p++){var m=this.v[this.w[a][p]];m.x=a*SCALE;m.z=p*SCALE;m.l();env.S++;k++}}};var x;CULLING=60;SPAWN_RATE=.2;ROLLING_DEMO_TIME=30;_loaded=_resources=0;material=[];textureSets=[];env={pause:!1,qa:0,ua:0,F:0,ca:!0,eb:!1,status:"none"};stat={Ka:[0,0,0,0,0],Ta:[0,0,0,0,0],Na:[0,0,0,0,0],Ua:[0,0,0,0,0],Oa:[0,0,0,0,0],Va:[0,0,0,0,0],units:function(a,b){var c=0;0>a?entities.forEach(function(a){a.type==b&&a.h&&c++}):entities.forEach(function(d){d.type==b&&d.c==a&&d.h&&c++});return c}};entities=[];markers=[];var y=new glMatrixArrayType(16),q=new glMatrixArrayType(16),ja=[];new glMatrixArrayType(16);
var Wa=Date.now(),B;
function La(){grid=new Va;markers[0]=new V(1,1,1,1,material[0]);markers[0].x=1*SCALE;markers[0].z=1*SCALE;markers[1]=new V(.3,.3,.3,.3,material[18]);markers[1].x=2;markers[1].z=15*SCALE;markers[2]=new V(.3,.3,.3,.3,material[5]);markers[2].x=15*SCALE;markers[2].z=2;markers[3]=new Quad(material[6]);markers[3].x=2*SCALE;markers[3].z=2*SCALE;markers[3].y=-1;markers.map(function(a){a.bind()});var a=X(W,20,.3,20);a.oa(1);target=focus=a;X(W,20,-.5,24).oa(2);X(Ua,20,-.5,40);X(Ua,30,-.5,60);X(Ua,40,-.5,80)}
function Xa(a,b){var c;c=b;var d=-1;0>c&&(c=0);for(var e=c?c:0;e<entities.length&&0>d;e++)a(entities[e])&&(d=e);if(0>d&&0<c)for(i=0;i<c&&i<entities.length&&0>d;i++)a(entities[i])&&(d=i);c=d;return 0>c?null:entities[c]}function Qa(){var a=entities.indexOf(target);a++;if(a=Xa(function(a){return a.h&&1==a.type?!0:!1},a))target=a,focus&&(focus=target)}function X(a,b,c,d){a=new a;a.Ma(b,c,d);b=!1;for(c=0;c<entities.length;c++)if(!entities[c].h){entities[c]=a;b=!0;break}b||entities.push(a);return a}
function Ma(){var a=Date.now(),b=(a-Wa)/1E3;window.M(Ma);try{for(ia(b);.05<b;)Ya(.05),b-=.05;Ya(b)}catch(c){console.log(c)}Wa=a;env.bb=Date.now()-a}
function Ya(a){env.pause||(env.qa+=a,env.ua+=a,env.F+=a,target&&target.h||Qa(),env.O?(env.I-=a,0>env.I&&(env.I=5+~~G(10),Qa()),env.F<ROLLING_DEMO_TIME&&(env.O=!1,focus=target)):env.F>ROLLING_DEMO_TIME&&(env.O=!0,env.I=7,focus=!1),markers.map(function(b){b.o(a)}),entities.map(function(b){b.h&&b.o(a)}),entities.map(function(b){b.h&&b.N&&(grid.N(b,a),entities.map(function(c){b!=c&&c.h&&b.N(c,a)}))}),ra()/4294967295<this.$a*a&&20>stat.units(-1,1)&&(console.log("spawning +1 drone"),X(W,~~G(grid.sa),-.5,
~~G(grid.sa))))}
function ia(a){x.viewport(0,0,x.ha,x.ga);x.clear(x.COLOR_BUFFER_BIT|x.DEPTH_BUFFER_BIT);if(_loaded===_resources&&B){ea();da();if(target){var b=target;w(y,.1,[1,0,0]);t(y,[0,-1,-2.5]);w(y,-b.pitch,[1,0,0]);w(y,-b.b,[0,1,0]);w(y,-b.u,[0,0,1]);t(y,[b.x,b.y,b.z])}else w(y,0,[1,0,0]),w(y,0,[0,1,0]),t(y,[0,0,0]);x.uniformMatrix4fv(B.Sa,!1,y);x.uniformMatrix4fv(B.va,!1,q);ka();env.S=0;grid.l();markers.map(function(a){env.S++;a.l()});entities.map(function(b){b.h&&Math.sqrt((target.x-b.x)*(target.x-b.x)+(target.z-
b.z)*(target.z-b.z))<CULLING&&(env.S++,b.l(a))});da();target&&env.ca?(overlayData=!0,overlay.innerHTML="Target: "+target.name+(focus?" Controling: "+focus.name:"")+" @"+grid.R(target.x)+"x"+grid.R(target.z)+"<br>"+Math.floor(100*target.x)/100+" -- "+Math.floor(100*target.z)/100+" -- "+Math.floor(100*target.y)/100+"<br>Shield: "+target.G+"<br>Energy: "+target.Z+"<br>Speed: "+Math.floor(target.speed)+"<hr><br>Goal: "+target.ra+(target&&target.m?"<br>Target: "+target.m+" @"+Math.round(target.P(target.m))+
"m":"")+"<br>Action: "+target.action+"<hr>FPS: "+Math.round(1/a)+"<br>Models: "+env.S+"<br>Drones: "+stat.units(-1,1)+"<br>Status: "+env.status+(env.O?"<br>= DEMO =":"")+(env.pause?"<br>= PAUSE =":"")):overlayData&&(overlay.innerHTML="",overlayData=!1)}};
