#!/bin/sh

# toolchain installation steps

npm update
npm upgrade

npm install --global gulp-cli
npm install --save-dev gulp
npm install harmonize
npm install gulp-closure-compiler
npm install gulp-htmlclean

